# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbe11b10d5197a8c637afec029b7349a7ab041e626d673b7adfbbaebbdfe5bed5b91cd3b5e76ed2be5aad105adfe9359fdf47b40ea61894ae1ffaa66d48a683e

test:
  secret_key_base: 67b8ee81928f45acd250d4ed67897358e162223dfa6adb61d908fe0cdfd7d16c5ef2c97a82b73e03e67f63423c83da43169dec287e42f8dfeac88256dd8ce085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
